name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/apps # go to app dir
            rm -rf nurvus-design-system/ # wipe out app for fresh build
            git clone https://github.com/UnfocusedDrive/nurvus-design-system.git # get latest
            cd nurvus-design-system # go to app dir
            npm install # get latest packages
            npm run styleguide:build #build styleguide

            # Staging
            rm -rf /var/www/unstable.memoryleak.ai/nurvus-design-system/ # remove directory to wipe all contents
            mkdir /var/www/unstable.memoryleak.ai/nurvus-design-system # recreate directory
            sudo mv -i styleguide/build/* /var/www/unstable.memoryleak.ai/nurvus-design-system/ # move build to serve dir
            echo 'Successfully deployed to unstable.memoryleak.ai/nurvus-design-system'

            # Production
            # rm -rf /var/www/nurvus.memoryleak.ai/ # remove directory to wipe all contents
            # mkdir /var/www/nurvus.memoryleak.ai # recreate directory
            # sudo mv -i styleguide/build/* /var/www/nurvus.memoryleak.ai/ # move build to serve dir
            # echo 'Successfully deployed to nurvus.memoryleak.ai'
